[package]
name = "substrate-instrumentation"
version = "2.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
log = { version = "0.4.8" }
parking_lot = "0.9.0"
quanta = "0.3"
tracing-core = "0.1.2"

substrate-telemetry = { path = "../telemetry" }